services:
  scp-bot-discord:
    build: .
    container_name: scp-bot-discord
    command: "python bot/src/bot.py"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./bot:/usr/app/bot
      - ./scripts:/usr/app/scripts
