services:
  scp-bot-discord:
    image: scp-bot-discord:latest
    container_name: scp-bot-discord
    command: "python bot/src/bot.py"
    env_file: ".env"
    volumes:
      - ./bot:/usr/app/bot
      - ./scripts:/usr/app/scripts
      - ${LOG_PATH}:${LOG_PATH}
